### ISSUE TITLE
mounting a YAML configuration file with .yml extension (not .yaml) isn't copied into /etc/dd-agent/conf.d

### ISSUE THREAD

**Issue by oryband** [DataDog/docker-dd-agent#85] opened 2016-05-01 09:21 UTC
The source of the problem is in this line: https://github.com/DataDog/docker-dd-agent/blob/4a05382ac2acb1b656c310380fe80ce5a92bb15b/entrypoint.sh#L43

`.yml` extension is a valid YAML extension and should also be taken into account.

**Comment by hkaj** [comment] 2016-05-02 12:08
Hi @oryband
Actually the root cause is in the dd-agent repository, not here. Configuration files need to have the `.yaml` extension to be considered. See https://github.com/DataDog/dd-agent/blob/5.7.4/config.py#L791 for example.
So it doesn't make sense to copy `.yml` files here because they would be ignored anyway.

You can open the same issue on the `dd-agent` if you think it's important but from the look of it, it's low priority for us. Feel free to submit a PR though, that would make the process faster :)

**Comment by oryband** [comment] 2016-05-02 12:37
@hkaj thanks. When the other repo implements this fix, this repo needs to be updated as well. Please keep this issue open until then.

**Comment by hkaj** [comment] 2016-05-26 09:28
The change was not perceived as particularly useful as `.yaml` is the only extension officially recommended. Closing.

**Closed by hkaj** 2016-05-26 09:28 UTC
