### ISSUE TITLE
HEALTHCHECK registers as an event in Datadog

### ISSUE THREAD

**Issue by Jwpe** [DataDog/docker-dd-agent#142] opened 2016-11-25 10:59 UTC
Hi there,

I am not sure if this is a bug or intended behaviour, but it seems like the new `HEALTHCHECK` command included in the `docker-dd-agent` Dockerfile since b8798219c69687001e6b1eb2b0983717429cf5e2 registers each health check update as an event that is sent to Datadog, regardless of the outcome of the health check. The body of each event is:

```
EXEC_START: /BIN/SH -C TEST $(/OPT/DATADOG-AGENT/EMBEDDED/BIN/PYTHON /OPT/DATADOG-AGENT/BIN/SUPERVISORCTL       -C /ETC/DD-AGENT/SUPERVISOR.CONF STATUS | AWK '{PRINT $2}' | EGREP -V 'RUNNING|EXITED' | WC -L)       -EQ 0 || EXIT 1   dd-agent  
EXEC_CREATE: /BIN/SH -C TEST $(/OPT/DATADOG-AGENT/EMBEDDED/BIN/PYTHON /OPT/DATADOG-AGENT/BIN/SUPERVISORCTL       -C /ETC/DD-AGENT/SUPERVISOR.CONF STATUS | AWK '{PRINT $2}' | EGREP -V 'RUNNING|EXITED' | WC -L)       -EQ 0 || EXIT 1  dd-agent
```

The result of this is an event spam from the `dd-agent` container, which somewhat drowns out important events in the Datadog interface. I've attached screenshots below to show what I mean:

**Event stream:**
![2016-11-25-103237_2180x533_scrot](https://cloud.githubusercontent.com/assets/1651943/20622512/1dc5d2b8-b2fb-11e6-9468-9b00223e63d0.png)

**Events on host dashboard:**
![2016-11-25-103945_1388x414_scrot](https://cloud.githubusercontent.com/assets/1651943/20622604/90ca32c2-b2fb-11e6-9b34-9e0137df1f54.png)

Is it intended that the agent container reports healthchecks as events? If so, is there a way to disable this through the configuration options? 

I've included bug report information in case it is useful. Please feel free to close this issue if the behaviour is intended!

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information)**

Command:

```bash
docker exec dd-agent /bin/bash /etc/init.d/datadog-agent status
```

Output:

```bash
\033[0;31mWarning: Known bug in Linux Kernel 3.18+ causes 'status' to fail.\033[0m
Calling 'info', instead...
====================
Collector (v 5.10.1)
====================

  Status date: 2016-11-25 10:48:18 (15s ago)
  Pid: 13
  Platform: Linux-4.7.3-coreos-r1-x86_64-with-debian-8.6
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======
  
    NTP offset: 0.0033 s
    System UTC time: 2016-11-25 10:48:33.763043
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d
  
  Hostnames
  =========
  
    ec2-hostname: ip-172-25-8-20.eu-west-1.compute.internal
    local-ipv4: 172.25.8.20
    local-hostname: ip-172-25-8-20.eu-west-1.compute.internal
    socket-hostname: 55fca74fae81
    public-hostname: ec2-52-213-172-9.eu-west-1.compute.amazonaws.com
    hostname: ip-172-25-8-20.eu-west-1.compute.internal
    instance-id: i-a4d40564
    public-ipv4: 52.213.172.9
    socket-fqdn: 55fca74fae81
  
  Checks
  ======
  
    ntp
    ---
      - Collected 0 metrics, 0 events & 0 service checks
  
    disk
    ----
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 0 service checks
  
    docker_daemon
    -------------
      - instance #0 [OK]
      - Collected 168 metrics, 0 events & 1 service check
  
  
  Emitters
  ========
  
    - http_emitter [OK]

====================
Dogstatsd (v 5.10.1)
====================

  Status date: 2016-11-25 10:48:31 (2s ago)
  Pid: 10
  Platform: Linux-4.7.3-coreos-r1-x86_64-with-debian-8.6
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 8844
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

====================
Forwarder (v 5.10.1)
====================

  Status date: 2016-11-25 10:48:31 (2s ago)
  Pid: 12
  Platform: Linux-4.7.3-coreos-r1-x86_64-with-debian-8.6
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 447 bytes
  Queue Length: 1
  Flush Count: 29915
  Transactions received: 13459
  Transactions flushed: 13458
  Transactions rejected: 0
  API Key Status: API Key is valid
```

**Additional environment details (Operating System, Cloud provider, etc):**
OS: CoreOS beta (1192.2.0)
Provider: AWS EC2

**Steps to reproduce the issue:**
1. Run the `docker-dd-agent` Docker container with the default init command as described in the [README]( https://github.com/DataDog/docker-dd-agent#quick-start)
2. Ensure that the agent has registered with the Datadog application
3. Observe the health checks appearing as events in the Datadog event stream every 5 minutes

**Describe the results you received:**
Health checks appear as events in the Datadog event stream, even if the health check is successful

**Describe the results you expected:**
Successful health checks on the `dd-agent` container do not trigger any events

**Comment by Jwpe** [comment] 2016-11-25 11:18
Looks like there's already some consideration for this in the [`dd-agent` code](https://github.com/DataDog/dd-agent/blob/afffaa56253af632f75941739d3b710247112ba8/checks.d/docker_daemon.py#L622):

```python
# health checks generate tons of these so we treat them separately and lower their priority
if event['status'].startswith('exec_create:') or event['status'].startswith('exec_start:'):
    low_prio_events.append((event, container_name))
```

However, the ones from the agent itself aren't ignored, nor does there appear to be a way to optionally ignore healthcheck events.

**Comment by hkaj** [comment] 2016-11-26 14:59
Hi @Jwpe 
Thanks for reaching out. I see what you're talking about, unfortunately Docker health checks are very simple. They just trigger `exec` events that are not flagged in any way as health check related.

The code you noticed is trying to reduce the spam induced by such events in the event stream, but we didn't want to get rid of them entirely as they can be useful.

On the other hand we now have a PR (https://github.com/DataDog/dd-agent/pull/2859) scheduled for 5.11 that collects health checks as datadog service checks. With this new option I think we could consider an event-exclusion mechanism to get rid of whole types of events all together. I'll add that to our backlog.

In the meantime a workaround would be to run the agent container with the `--no-healthcheck` flag to disable the health check. Would that work for you?

**Comment by Jwpe** [comment] 2016-11-28 10:02
@hkaj thanks so much for the prompt response! I think your event exclusion idea makes sense, once health checks are separated out as a datadog service check. In the meantime, I'll use the flag you suggested to suppress the events, since I don't really need the health check for the container.

Should I close out this issue, or is it worth keeping it open?

**Comment by hkaj** [comment] 2016-11-28 10:56
Thanks for the feedbck @Jwpe. Let's keep it open for tracking. We'll close it once we get around to implementing this feature.

**Comment by blackstar257** [comment] 2016-12-06 06:26
I too just recently ran across this. I will go without the healthcheck for now. Thanks

**Comment by davidfontenot** [comment] 2017-04-04 19:34
I'm having some issues with the new settings for the docker integration. I've confirmed I have at least 5.12.0 (using the docker image for 5.12.3), and have tried setting `health_service_check_whitelist: []` and `health_service_checks: false` (I only see this one in the PR) to turn off these events. After reloading datadog-agent I'm still seeing health check events.

**Comment by Lawouach** [comment] 2017-04-18 22:27
Hi @Jwpe, maybe I'm not looking it right, but I can't find any piece of code regarding that `--no-healthcheck` . Was it ever implemented?

I echo the tiredness of the flood those events generate :/

**Comment by scippio** [comment] 2017-04-23 16:36
I had to turn healthcheck off because my Datadog account was flooded by this error events.
```
healthcheck:
      disable: true
```

**Comment by Jwpe** [comment] 2017-04-24 08:09
@Lawouach it's a Docker-level CLI flag! Here's a stripped down example of how I'm running the container:

```bash
docker run --no-healthcheck datadog/docker-dd-agent
```
There are some other flags and volume bindings in there but that's the usage of `--no-healthcheck`

**Comment by abonillasuse** [comment] 2017-09-07 15:56
Is there a way to pass this to the helm chart from
https://github.com/kubernetes/charts/tree/master/stable/datadog
any way to add it to the values.yaml?

**Comment by bgerstle** [comment] 2017-09-08 20:23
I'm running datadog-agent 5.17 and not finding container health checks in datadog as a check or a metric, but I am seeing this event spam. Do I need to be running datadog in a container for this to work?

**Comment by irabinovitch** [comment] 2017-11-03 12:49
As of September we no longer display the health check as an event.  A comprehensive list of events we filter by default is available here: https://help.datadoghq.com/hc/en-us/articles/115004125863-Docker-ECS-Kubernetes-Events

If you would like these events you can file a support ticket to request they be enabled.

**Closed by irabinovitch** 2017-11-03 12:49 UTC
