### ISSUE TITLE
core : datadog.conf log_file directives in wrong place (release 12.4.5180)

### ISSUE THREAD

**Issue by ggpretorius** [DataDog/docker-dd-agent#252] opened 2017-10-11 06:55 UTC
Hello,

This seems like an obvious config file issue so not going to run the detailed bug reporting steps.

version : docker-dd-agent latest-alpine release 12.4.5180 (agent 5.18.0)
file : /opt/datadog-agent/agent/datadog.conf

These directives appear last in the config file, which puts them under the [trace.ignore] section, and it looks like it is ignored as a result:
```
collector_log_file = /opt/datadog-agent/logs/collector.log
forwarder_log_file = /opt/datadog-agent/logs/forwarder.log
dogstatsd_log_file = /opt/datadog-agent/logs/dogstatsd.log
jmxfetch_log_file = /opt/datadog-agent/logs/jmxfetch.log
```

The effect is the default log locations are used by the agent and since those locations do not exist in the container file system, logging to file fails.

moving those directives to the [Main] section solves the issue

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Steps to reproduce the issue:**
1. start up an instance of : docker-dd-agent latest-alpine release 12.4.5180 (agent 5.18.0)

**Describe the results you received:**
run : /opt/datadog-agent/bin/agent info
you will see several of these in the output:
```
Log file is unwritable: [default log file]
```

nothing gets logged to `/opt/datadog-agent/logs`

**Describe the results you expected:**
You should see logs for the various components in their respective log files:
```
/opt/datadog-agent/logs/collector.log
/opt/datadog-agent/logs/forwarder.log
/opt/datadog-agent/logs/dogstatsd.log
/opt/datadog-agent/logs/jmxfetch.log
```

**Comment by hkaj** [comment] 2017-10-12 12:18
Hi @ggpretorius 
Thanks for the report, and sorry for the trouble. We are working on this.

**Comment by nmuesch** [comment] 2017-10-13 14:36
Hey, thanks for reporting this and apologies for the inconvenience. This PR is merged that will make the log lines more resilient to changes made to the Datadog.conf.example file so this doesn't happen in the future - https://github.com/DataDog/dd-agent/pull/3545

**Comment by hkaj** [comment] 2017-10-13 15:39
We just rebuilt the image, the issue is now fixed.
Thanks again for reporting this issue, and please let us know if you have any more issue.

**Closed by hkaj** 2017-10-13 15:39 UTC
