### ISSUE TITLE
dd-agent crashes docker on boot

### ISSUE THREAD

**Issue by thedug** [DataDog/docker-dd-agent#19] opened 2015-04-08 18:16 UTC
I'm running dd-agent with --restart=always so that docker will restart the container on boot.

When I do this docker crashes and will not run until I delete the dd-agent container from /var/lib/docker/containers.

**Comment by alq666** [comment] 2015-04-09 20:37
Thanks for the report, @thedug. Do you have some logs you can share with us? Or maybe a way to reproduce the issue?

**Comment by thedug** [comment] 2015-04-09 22:47
Repo steps.

Launch an ubuntu 14.04 host
Execute the following command..
   docker run --restart=always -d --privileged --name dd-agent -h
`hostname` -v /var/run/docker.sock:/var/run/docker.sock -v
/proc/mounts:/host/proc/mounts:ro -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
-e API_KEY={your_api_key_here} datadog/docker-dd-agent
Reboot
See docker has crashed and won't restart

**Comment by alq666** [comment] 2015-04-30 01:46
@LotharSee does that sound familiar? Left-over pid file?

**Comment by thedug** [comment] 2015-05-01 14:10
Note.. I just realized that it prints out the offending container right before it blows up. It's always the ddagent container.

INFO[0000] -job allocate_interface(e96348c5b4fca4fd9496de566d79ddf01d55661ad181cd10c3a024d5e8c6c286) = OK (0)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x76ff18]

goroutine 9 [running]:
github.com/docker/docker/volumes.(*Volume).RemoveContainer(0x0, 0xc2082a3040, 0x40)
	/go/src/github.com/docker/docker/volumes/volume.go:78 +0x98
github.com/docker/docker/daemon.(*Mount).initialize(0xc2082ae3c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/volumes.go:93 +0x1b0
github.com/docker/docker/daemon.(*Container).createVolumes(0xc2081adc00, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/volumes.go:69 +0xd9
github.com/docker/docker/daemon.(*Container).prepareVolumes(0xc2081adc00, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/volumes.go:48 +0x5e
github.com/docker/docker/daemon.(*Container).Start(0xc2081adc00, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:354 +0x290
github.com/docker/docker/daemon.(*Daemon).restore(0xc2080e4f20, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:401 +0x1199
github.com/docker/docker/daemon.NewDaemonFromDirectory(0x12eb800, 0xc2080e4a50, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:989 +0x25e6
github.com/docker/docker/daemon.NewDaemon(0x12eb800, 0xc2080e4a50, 0xc208000240, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/daemon.go:781 +0x44
main.func·002()
	/go/src/github.com/docker/docker/docker/daemon.go:104 +0x46
created by main.mainDaemon
	/go/src/github.com/docker/docker/docker/daemon.go:127 +0x43d

goroutine 1 [chan receive]:
github.com/docker/docker/api/server.ServeApi(0xc208030600, 0x7f4eb4b10c98)
	/go/src/github.com/docker/docker/api/server/server.go:1634 +0x5a1
github.com/docker/docker/engine.(*Job).Run(0xc208030600, 0x0, 0x0)
	/go/src/github.com/docker/docker/engine/job.go:83 +0x936
main.mainDaemon()
	/go/src/github.com/docker/docker/docker/daemon.go:142 +0x6a7
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:73 +0x4c0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [chan receive]:
github.com/docker/docker/pkg/signal.func·002()
	/go/src/github.com/docker/docker/pkg/signal/trap.go:30 +0x8f
created by github.com/docker/docker/pkg/signal.Trap
	/go/src/github.com/docker/docker/pkg/signal/trap.go:53 +0x357

goroutine 10 [chan receive]:
github.com/docker/docker/pkg/listenbuffer.(*defaultListener).Accept(0xc208199040, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/listenbuffer/buffer.go:43 +0xb6
net/http.(*Server).Serve(0xc2081a2600, 0x7f4eb4b122c0, 0xc208199040, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
github.com/docker/docker/api/server.(*HttpServer).Serve(0xc208199320, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:51 +0x4d
github.com/docker/docker/api/server.func·006()
	/go/src/github.com/docker/docker/api/server/server.go:1629 +0x2b8
created by github.com/docker/docker/api/server.ServeApi
	/go/src/github.com/docker/docker/api/server/server.go:1630 +0x526

goroutine 34 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208149e00)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 37 [chan receive]:
github.com/docker/docker/daemon.(*statsCollector).run(0xc20827de20)
	/go/src/github.com/docker/docker/daemon/stats_collector.go:79 +0x8e
created by github.com/docker/docker/daemon.newStatsCollector
	/go/src/github.com/docker/docker/daemon/stats_collector.go:28 +0xc3

**Comment by alq666** [comment] 2015-05-01 18:33
@thedug forgot to ask, which version of docker are you running?

**Comment by thedug** [comment] 2015-05-01 23:45
I've seen the issue with docker 1.5 and 1.6

**Comment by alq666** [comment] 2015-09-02 23:02
@thedug I've tried to reproduce to no avail on 1.6.2. Still an issue?

**Comment by remh** [comment] 2015-09-11 21:06
Unable to reproduce. Closing this issue.

**Closed by remh** 2015-09-11 21:06 UTC
